// UI/app/cars/page.tsx
"use client"

import type React from "react"
import { useState, useEffect } from "react"
import { carService } from "../services/carService"
import type { Car } from "../types/car"
import DataTable from "../components/DataTable"
import ExcelImportExport from "../components/ExcelImportExport"
import { useLanguage } from "../contexts/LanguageContext"

export default function CarsPage() {
  const { t } = useLanguage()
  const [cars, setCars] = useState<Car[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState("")
  const [editingCar, setEditingCar] = useState<Car | null>(null)
  const [showForm, setShowForm] = useState(false)
  const [formData, setFormData] = useState({
    model: "",
    plateNumber: "",
    capacity: 1,
    color: "",
    year: new Date().getFullYear(),
    notes: "",
  })

  useEffect(() => {
    loadCars()
  }, [])

  const loadCars = async () => {
    try {
      setIsLoading(true)
      const data = await carService.getCars()
      setCars(data)
    } catch (err) {
      setError("Failed to load cars")
      console.error(err)
    } finally {
      setIsLoading(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      if (editingCar) {
        await carService.updateCar(editingCar.id, { ...editingCar, ...formData })
      } else {
        await carService.createCar(formData)
      }
      await loadCars()
      resetForm()
    } catch (err) {
      setError("Failed to save car")
      console.error(err)
    }
  }

  const handleEdit = (car: Car) => {
    setEditingCar(car)
    setFormData({
      model: car.model,
      plateNumber: car.plateNumber,
      capacity: car.capacity,
      color: car.color,
      year: car.year,
      notes: car.notes,
    })
    setShowForm(true)
  }

  const handleDelete = async (id: number) => {
    if (!confirm("Are you sure you want to delete this car?")) return

    try {
      await carService.deleteCar(id)
      await loadCars()
    } catch (err) {
      setError("Failed to delete car")
      console.error(err)
    }
  }

  const resetForm = () => {
    setEditingCar(null)
    setShowForm(false)
    setFormData({
      model: "",
      plateNumber: "",
      capacity: 1,
      color: "",
      year: new Date().getFullYear(),
      notes: "",
    })
  }

  const handleImport = async (importedData: any[]) => {
    try {
      for (const carData of importedData) {
        await carService.createCar(carData)
      }
      await loadCars()
    } catch (err) {
      setError("Failed to import cars")
      console.error(err)
    }
  }

  const handleExport = async () => {
    // Export functionality is handled by the ExcelImportExport component
  }

  const columns = [
    {
      key: "model",
      label: t("cars.model"),
      sortable: true,
    },
    {
      key: "plateNumber",
      label: t("cars.plateNumber"),
      sortable: true,
    },
    {
      key: "capacity",
      label: t("cars.capacity"),
      sortable: true,
      render: (value: number) => `${value} ${t("cars.people")}`,
    },
    {
      key: "color",
      label: t("cars.color"),
      render: (value: string) => (
        <div className="flex items-center">
          <div
            className="w-4 h-4 rounded-full mr-2 border border-gray-300"
            style={{ backgroundColor: value.toLowerCase() }}
          ></div>
          {value}
        </div>
      ),
    },
    {
      key: "year",
      label: t("cars.year"),
      sortable: true,
    },
    {
      key: "isActive",
      label: t("common.status"),
      render: (value: boolean) => (
        <span
          className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
            value ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"
          }`}
        >
          {value ? t("common.active") : t("common.inactive")}
        </span>
      ),
    },
  ]

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="loading-spinner mx-auto mb-4"></div>
            <p className="text-gray-600">{t("common.loading")}</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">{t("cars.title")}</h1>
              <p className="mt-2 text-gray-600">{t("cars.subtitle")}</p>
            </div>
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4">
              <ExcelImportExport
                type="cars"
                onImport={handleImport}
                onExport={handleExport}
                data={cars}
                filename={`cars_${new Date().toISOString().split("T")[0]}.xlsx`}
              />
              <button onClick={() => setShowForm(true)} className="btn-primary whitespace-nowrap flex items-center">
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
                {t("cars.addCar")}
              </button>
            </div>
          </div>
        </div>

        {error && (
          <div className="alert alert-error mb-6">
            <p>{error}</p>
          </div>
        )}

        {/* Add/Edit Form Modal */}
        {showForm && (
          <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
            <div className="relative top-20 mx-auto p-5 border w-11/12 md:w-3/4 lg:w-1/2 shadow-lg rounded-md bg-white">
              <div className="mt-3">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg font-medium text-gray-900">
                    {editingCar ? t("cars.editCar") : t("cars.addNewCar")}
                  </h3>
                  <button onClick={resetForm} className="text-gray-400 hover:text-gray-600">
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <label className="form-label">{t("cars.model")} *</label>
                      <input
                        type="text"
                        value={formData.model}
                        onChange={(e) => setFormData({ ...formData, model: e.target.value })}
                        className="form-input"
                        placeholder={t("cars.modelPlaceholder")}
                        required
                      />
                    </div>

                    <div>
                      <label className="form-label">{t("cars.plateNumber")} *</label>
                      <input
                        type="text"
                        value={formData.plateNumber}
                        onChange={(e) => setFormData({ ...formData, plateNumber: e.target.value })}
                        className="form-input"
                        placeholder={t("cars.platePlaceholder")}
                        required
                      />
                    </div>

                    <div>
                      <label className="form-label">{t("cars.capacity")} *</label>
                      <input
                        type="number"
                        value={formData.capacity}
                        onChange={(e) => setFormData({ ...formData, capacity: Number.parseInt(e.target.value) })}
                        className="form-input"
                        placeholder={t("cars.capacityPlaceholder")}
                        min="1"
                        max="100"
                        required
                      />
                    </div>

                    <div>
                      <label className="form-label">{t("cars.color")}</label>
                      <select
                        value={formData.color}
                        onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                        className="form-input"
                      >
                        <option value="">{t("cars.selectColor")}</option>
                        <option value="White">White</option>
                        <option value="Black">Black</option>
                        <option value="Blue">Blue</option>
                        <option value="Red">Red</option>
                        <option value="Silver">Silver</option>
                        <option value="Gray">Gray</option>
                      </select>
                    </div>

                    <div>
                      <label className="form-label">{t("cars.year")}</label>
                      <input
                        type="number"
                        value={formData.year}
                        onChange={(e) => setFormData({ ...formData, year: Number.parseInt(e.target.value) })}
                        className="form-input"
                        min="1990"
                        max="2030"
                      />
                    </div>

                    <div className="md:col-span-2">
                      <label className="form-label">{t("cars.notes")}</label>
                      <textarea
                        value={formData.notes}
                        onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                        className="form-input"
                        rows={3}
                        placeholder={t("cars.notesPlaceholder")}
                      />
                    </div>
                  </div>

                  <div className="flex justify-end space-x-4 pt-4 border-t">
                    <button type="button" onClick={resetForm} className="btn-secondary">
                      {t("common.cancel")}
                    </button>
                    <button type="submit" className="btn-primary">
                      {editingCar ? t("common.update") : t("common.add")} {t("nav.cars")}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        )}

        {/* Data Table */}
        <DataTable
          data={cars}
          columns={columns}
          onEdit={handleEdit}
          onDelete={handleDelete}
          searchable={true}
          filterable={true}
          itemsPerPage={10}
        />
      </div>
    </div>
  )
}

// UI/src/app/components/cars/cars.component.ts
import { Component, type OnInit } from "@angular/core"
import { CommonModule } from "@angular/common"
import { FormsModule, ReactiveFormsModule, type FormBuilder, type FormGroup, Validators } from "@angular/forms"
import type { CarService } from "../../services/car.service"
import type { Car } from "../../models/car.model"

@Component({
  selector: "app-cars",
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  template: `
    <div class="min-h-screen bg-gray-50 py-8">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="mb-8">
          <h1 class="text-3xl font-bold text-gray-900">Car Management</h1>
          <p class="mt-2 text-gray-600">Manage your fleet of vehicles</p>
        </div>

        <!-- Add/Edit Car Form -->
        <div class="bg-white shadow rounded-lg p-6 mb-8">
          <h2 class="text-xl font-semibold mb-4">{{editingCar ? 'Edit Car' : 'Add New Car'}}</h2>
          <form [formGroup]="carForm" (ngSubmit)="saveCar()" class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="form-label">Model</label>
              <input type="text" formControlName="model" class="form-input" placeholder="Enter car model">
              <div *ngIf="carForm.get('model')?.invalid && carForm.get('model')?.touched" class="text-red-500 text-sm mt-1">
                Model is required
              </div>
            </div>

            <div>
              <label class="form-label">Plate Number</label>
              <input type="text" formControlName="plateNumber" class="form-input" placeholder="Enter plate number">
              <div *ngIf="carForm.get('plateNumber')?.invalid && carForm.get('plateNumber')?.touched" class="text-red-500 text-sm mt-1">
                Plate number is required
              </div>
            </div>

            <div>
              <label class="form-label">Capacity</label>
              <input type="number" formControlName="capacity" class="form-input" placeholder="Enter capacity" min="1" max="100">
              <div *ngIf="carForm.get('capacity')?.invalid && carForm.get('capacity')?.touched" class="text-red-500 text-sm mt-1">
                Capacity must be between 1 and 100
              </div>
            </div>

            <div>
              <label class="form-label">Color</label>
              <input type="text" formControlName="color" class="form-input" placeholder="Enter color">
            </div>

            <div>
              <label class="form-label">Year</label>
              <input type="number" formControlName="year" class="form-input" placeholder="Enter year" min="1990" max="2030">
            </div>

            <div class="md:col-span-2">
              <label class="form-label">Notes</label>
              <textarea formControlName="notes" class="form-input" rows="3" placeholder="Enter any additional notes"></textarea>
            </div>

            <div class="md:col-span-2 flex justify-end space-x-4">
              <button type="button" (click)="cancelEdit()" class="btn-secondary">
                Cancel
              </button>
              <button type="submit" [disabled]="carForm.invalid || isLoading" class="btn-primary ">
                {{isLoading ? 'Saving...' : (editingCar ? 'Update Car' : 'Add Car')}}
              </button>
            </div>
          </form>
        </div>

        <!-- Cars List -->
        <div class="bg-white shadow rounded-lg overflow-hidden">
          <div class="px-6 py-4 border-b border-gray-200">
            <h2 class="text-xl font-semibold text-gray-900">Cars ({{cars.length}})</h2>
          </div>

          <div *ngIf="isLoading && cars.length === 0" class="p-8 text-center">
            <div class="loading-spinner mx-auto mb-4"></div>
            <p class="text-gray-600">Loading cars...</p>
          </div>

          <div *ngIf="!isLoading && cars.length === 0" class="p-8 text-center">
            <p class="text-gray-600">No cars found. Add your first car above.</p>
          </div>

          <div *ngIf="cars.length > 0" class="overflow-x-auto">
            <table class="table">
              <thead>
                <tr>
                  <th>Model</th>
                  <th>Plate Number</th>
                  <th>Capacity</th>
                  <th>Color</th>
                  <th>Year</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200">
                <tr *ngFor="let car of cars" class="hover:bg-gray-50">
                  <td class="font-medium">{{car.model}}</td>
                  <td>{{car.plateNumber}}</td>
                  <td>{{car.capacity}} people</td>
                  <td>
                    <span class="inline-flex items-center">
                      <span class="w-3 h-3 rounded-full mr-2" [style.background-color]="car.color.toLowerCase()"></span>
                      {{car.color}}
                    </span>
                  </td>
                  <td>{{car.year}}</td>
                  <td>
                    <span class="inline-flex px-2 py-1 text-xs font-semibold rounded-full"
                          [class]="car.isActive ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'">
                      {{car.isActive ? 'Active' : 'Inactive'}}
                    </span>
                  </td>
                  <td>
                    <div class="flex space-x-2">
                      <button (click)="editCar(car)" class="text-blue-600 hover:text-blue-800 text-sm font-medium">
                        Edit
                      </button>
                      <button (click)="deleteCar(car.id)" class="text-red-600 hover:text-red-800 text-sm font-medium">
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Error Message -->
        <div *ngIf="errorMessage" class="alert alert-error mt-6">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3">
              <h3 class="text-sm font-medium text-red-800">Error</h3>
              <p class="text-sm text-red-700 mt-1">{{errorMessage}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class CarsComponent implements OnInit {
  cars: Car[] = []
  carForm: FormGroup
  editingCar: Car | null = null
  isLoading = false
  errorMessage = ""

  constructor(
    private carService: CarService,
    private fb: FormBuilder,
  ) {
    this.carForm = this.fb.group({
      model: ["", Validators.required],
      plateNumber: ["", Validators.required],
      capacity: [1, [Validators.required, Validators.min(1), Validators.max(100)]],
      color: [""],
      year: [new Date().getFullYear(), [Validators.min(1990), Validators.max(2030)]],
      notes: [""],
    })
  }

  ngOnInit() {
    this.loadCars()
  }

  loadCars() {
    this.isLoading = true
    this.errorMessage = ""

    this.carService.getCars().subscribe({
      next: (cars) => {
        this.cars = cars
        this.isLoading = false
      },
      error: (error) => {
        console.error("Error loading cars:", error)
        this.errorMessage = "Failed to load cars. Please check your connection and try again."
        this.isLoading = false
      },
    })
  }

  saveCar() {
    if (this.carForm.invalid) return

    this.isLoading = true
    this.errorMessage = ""

    const carData = this.carForm.value

    if (this.editingCar) {
      // Update existing car
      const updatedCar = { ...this.editingCar, ...carData }
      this.carService.updateCar(updatedCar).subscribe({
        next: () => {
          this.loadCars()
          this.cancelEdit()
          this.isLoading = false
        },
        error: (error) => {
          console.error("Error updating car:", error)
          this.errorMessage = "Failed to update car. Please try again."
          this.isLoading = false
        },
      })
    } else {
      // Create new car
      this.carService.createCar(carData).subscribe({
        next: () => {
          this.loadCars()
          this.carForm.reset()
          this.isLoading = false
        },
        error: (error) => {
          console.error("Error creating car:", error)
          this.errorMessage = "Failed to create car. Please try again."
          this.isLoading = false
        },
      })
    }
  }

  editCar(car: Car) {
    this.editingCar = car
    this.carForm.patchValue({
      model: car.model,
      plateNumber: car.plateNumber,
      capacity: car.capacity,
      color: car.color,
      year: car.year,
      notes: car.notes,
    })
  }

  cancelEdit() {
    this.editingCar = null
    this.carForm.reset()
    this.errorMessage = ""
  }

  deleteCar(id: number) {
    if (!confirm("Are you sure you want to delete this car?")) return

    this.carService.deleteCar(id).subscribe({
      next: () => {
        this.loadCars()
      },
      error: (error) => {
        console.error("Error deleting car:", error)
        this.errorMessage = "Failed to delete car. Please try again."
      },
    })
  }
}
